### ISSUE TITLE
TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by edeutsch** [dhmay/param-medic#2]
Hi, I have installed Param-medic and it works great on most of the example mzML files at:
https://noble.gs.washington.edu/proj/param-medic/
I get what appears to be good output for 9 of the 11 mzML files.

But I get an error on 140915_SKBR3B-TMT_SAX_FT.mzML

python --version
Python 2.7.16

/proteomics/sw/python/param-medic/bin/param-medic 140915_SKBR3B-TMT_SAX_FT.mzML
2019-08-20 21:05:07,510 INFO: Processing input file 140915_SKBR3B-TMT_SAX_FT.mzML...
2019-08-20 21:05:11,388 INFO:   processed 0 total spectra in 3.9 seconds...
Traceback (most recent call last):
  File "/proteomics/sw/python/param-medic/bin/param-medic", line 377, in <module>
    main()
  File "/proteomics/sw/python/param-medic/bin/param-medic", line 234, in main
    run_attribute_detector.process_spectrum(spectrum, binned_spectrum)
  File "build/bdist.linux-x86_64/egg/parammedic/errorcalc.py", line 156, in process_spectrum
  File "build/bdist.linux-x86_64/egg/parammedic/errorcalc.py", line 514, in process_spectrum
TypeError: unhashable type: 'list'

**Comment by dhmay** [comment]
Like Issue #3, this is an issue with the mzML version of the file but not the .ms2. However, param-medic shouldn't be throwing that error. I'll have a look.
