### ISSUE TITLE
--enzyme flag gives error

### ISSUE THREAD

**Issue by edeutsch** [dhmay/param-medic#4]
I tried using the --enzyme flag this this seems useful, but it always gives an error. Latest code from trunk on Python 2.7.16

Without works great:
/proteomics/sw/python/param-medic/bin/param-medic Adult_Kidney_bRP_Velos_8_f01.mzML
2019-08-20 21:25:42,087 INFO: Processing input file Adult_Kidney_bRP_Velos_8_f01.mzML...
2019-08-20 21:25:42,492 INFO:   processed 0 total spectra in 0.4 seconds...
2019-08-20 21:25:43,324 INFO:   processed 1000 total spectra in 1.2 seconds...
2019-08-20 21:25:44,204 INFO:   processed 2000 total spectra in 2.1 seconds...
2019-08-20 21:25:45,110 INFO:   processed 3000 total spectra in 3.0 seconds...
2019-08-20 21:25:46,024 INFO:   processed 4000 total spectra in 3.9 seconds...
2019-08-20 21:25:46,951 INFO:   processed 5000 total spectra in 4.9 seconds...
2019-08-20 21:25:47,869 INFO:   processed 6000 total spectra in 5.8 seconds...
2019-08-20 21:25:48,784 INFO:   processed 7000 total spectra in 6.7 seconds...
2019-08-20 21:25:49,687 INFO:   processed 8000 total spectra in 7.6 seconds...
2019-08-20 21:25:50,453 INFO: Using 841 peak pairs for precursor error estimation.
2019-08-20 21:25:50,458 INFO: Using 4205 peak pairs for fragment error estimation.
2019-08-20 21:25:50,463 INFO: Precursor and fragment error summary:
2019-08-20 21:25:50,464 INFO: precursor standard deviation: 0.594776 ppm
2019-08-20 21:25:50,464 INFO: fragment standard deviation: 0.940726 ppm
2019-08-20 21:25:50,624 INFO: SILAC: no labeling detected
2019-08-20 21:25:50,626 INFO: iTRAQ: no reporter ions detected
2019-08-20 21:25:50,626 INFO: TMT: no reporter ions detected
2019-08-20 21:25:50,626 INFO: Phosphorylation: not detected
2019-08-20 21:25:50,626 INFO: 
Search parameter recommendations:
2019-08-20 21:25:50,626 INFO: Precursor error: 22.25 ppm
2019-08-20 21:25:50,626 INFO: Fragment bin size: 0.0040 Th
file	precursor_prediction_ppm	precursor_sigma_ppm	fragment_prediction_th	fragment_sigma_ppm	SILAC_4Da_present	SILAC_4Da_statistic	SILAC_6Da_presentSILAC_6Da_statistic	SILAC_8Da_present	SILAC_8Da_statistic	SILAC_10Da_present	SILAC_10Da_statistic	iTRAQ_8plex_present	iTRAQ_8plex_statistic	iTRAQ_4plex_present	iTRAQ_4plex_statistic	TMT_6plex_present	TMT_6plex_statistic	TMT_10plex_present	TMT_10plex_statistic	TMT_2plex_present	TMT_2plex_statistic	phospho_present	phospho_statistic
Adult_Kidney_bRP_Velos_8_f01.mzML	22.2470	0.5948	0.0040	0.9407	F	-2.4835	F	-0.8205	F	-0.2148	F	-0.5837	F	-1.0777	F	-1.1027	F	0.4232	F	0	F	-0.8653	F	0.0214

But same file with --enzyme flag:

/proteomics/sw/python/param-medic/bin/param-medic --enzyme Adult_Kidney_bRP_Velos_8_f01.mzML
2019-08-20 21:26:18,684 INFO: Processing input file Adult_Kidney_bRP_Velos_8_f01.mzML...
2019-08-20 21:26:19,086 INFO:   processed 0 total spectra in 0.4 seconds...
2019-08-20 21:26:19,911 INFO:   processed 1000 total spectra in 1.2 seconds...
2019-08-20 21:26:20,790 INFO:   processed 2000 total spectra in 2.1 seconds...
2019-08-20 21:26:21,695 INFO:   processed 3000 total spectra in 3.0 seconds...
2019-08-20 21:26:22,606 INFO:   processed 4000 total spectra in 3.9 seconds...
2019-08-20 21:26:23,528 INFO:   processed 5000 total spectra in 4.8 seconds...
2019-08-20 21:26:24,436 INFO:   processed 6000 total spectra in 5.8 seconds...
2019-08-20 21:26:25,341 INFO:   processed 7000 total spectra in 6.7 seconds...
2019-08-20 21:26:26,237 INFO:   processed 8000 total spectra in 7.6 seconds...
2019-08-20 21:26:26,993 INFO: Using 841 peak pairs for precursor error estimation.
2019-08-20 21:26:26,998 INFO: Using 4205 peak pairs for fragment error estimation.
2019-08-20 21:26:27,003 INFO: Precursor and fragment error summary:
2019-08-20 21:26:27,003 INFO: precursor standard deviation: 0.594776 ppm
2019-08-20 21:26:27,003 INFO: fragment standard deviation: 0.940726 ppm
2019-08-20 21:26:27,163 INFO: SILAC: no labeling detected
2019-08-20 21:26:27,164 INFO: iTRAQ: no reporter ions detected
2019-08-20 21:26:27,164 INFO: TMT: no reporter ions detected
2019-08-20 21:26:27,164 INFO: Phosphorylation: not detected
2019-08-20 21:26:27,164 INFO: 
Search parameter recommendations:
2019-08-20 21:26:27,164 INFO: Precursor error: 22.25 ppm
2019-08-20 21:26:27,165 INFO: Fragment bin size: 0.0040 Th
2019-08-20 21:26:27,165 INFO: Inferring enzyme...
2019-08-20 21:26:27,165 INFO: Processing input file Adult_Kidney_bRP_Velos_8_f01.mzML...
Traceback (most recent call last):
  File "/proteomics/sw/python/param-medic/bin/param-medic", line 377, in <module>
    main()
  File "/proteomics/sw/python/param-medic/bin/param-medic", line 302, in main
    for spectrum in generate_spectra(reopened_infile):
TypeError: generate_spectra() takes exactly 2 arguments (1 given)

**Comment by dhmay** [comment]
Oops! Enzyme inference was a speculative feature that never got properly implemented. That argument should've stayed on a branch. I'll chop it out.

**Comment by dhmay** [comment]
I got rid of --enzyme. It was a fun idea, but it was never tested thoroughly enough to be ready for outside consumption.
